export { WebAppProvider } from "./provider";

export {
    useAddToHomeScreen,
    useAccelerometer,
    useBiometricManager,
    useClosingConfirmation,
    useClose,
    useCloudStorage,
    useDeviceOrientation,
    useDownloadFile,
    useExpand,
    useFullscreen,
    useGyroscope,
    useHaptic,
    useHomeScreen,
    useInitData,
    useLocationManager,
    useOpenInvoice,
    useOpenLink,
    useOpenTelegramLink,
    useOrientationLock,
    useReady,
    useReadTextFromClipboard,
    useRequestContact,
    useRequestEmojiStatusAccess,
    useRequestWriteAccess,
    useSafeAreaInsets,
    useScanQrPopup,
    useSendData,
    useSetEmojiStatus,
    useShareMessage,
    useShareToStory,
    useShowAlert,
    useShowConfirm,
    useShowPopup,
    useSwitchInlineQuery,
    useThemeParams,
    useVerticalSwipes,
    useViewport,
    useWebApp,
    useWebAppEvent,
} from "./hooks";

export {
    MainButton,
    SecondaryButton,
    BackButton,
    SettingsButton,
} from "./buttons";

export { SetupWebApp } from "./lib";
